import type {
  HighlightBundle,
  HighlightDef,
} from "@/features/highlight-mapper/highlight-mapper.types";

const DEFAULT_THEME_NAME = "oshicolor";

/**
 * HighlightDef を Lua テーブルリテラルに変換する
 *
 * @example
 * formatHighlightDef({ fg: "#c8c8c8", bg: "#1a1a2e", bold: true })
 * // => '{ fg = "#c8c8c8", bg = "#1a1a2e", bold = true }'
 */
const formatHighlightDef = (def: HighlightDef): string => {
  const parts: string[] = [];

  if (def.fg) parts.push(`fg = "${def.fg}"`);
  if (def.bg) parts.push(`bg = "${def.bg}"`);
  if (def.bold) parts.push("bold = true");
  if (def.italic) parts.push("italic = true");
  if (def.undercurl) parts.push("undercurl = true");

  return `{ ${parts.join(", ")} }`;
};

/**
 * HighlightBundle から Neovim 用 Lua カラースキーム文字列を生成する
 */
export const generateLuaColorscheme = (
  bundle: HighlightBundle,
  themeName: string = DEFAULT_THEME_NAME,
): string => {
  const header = [
    `-- ${themeName}: generated by oshicolor`,
    'vim.cmd("hi clear")',
    'if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end',
    "vim.o.termguicolors = true",
    'vim.o.background = "dark"',
    `vim.g.colors_name = "${themeName}"`,
    "",
    "local hi = vim.api.nvim_set_hl",
  ];

  const highlights = Object.entries(bundle.highlights).map(
    ([group, def]) => `hi(0, "${group}", ${formatHighlightDef(def)})`,
  );

  return [...header, ...highlights, ""].join("\n");
};
